version: '3.8'

services:
  aj-nexus:
    build: .
    container_name: aj-nexus
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - APPLEJUICE_CORE_HOST=192.168.178.222
      - APPLEJUICE_CORE_PORT=9854
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/status', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Für erweiterte Setups
networks:
  default:
    name: applejuice-network